<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('subjects')->insert([
            [
                'course_code' => 'CS 111',
                'description' => 'Introduction to Computing',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ], 
            [
                'course_code' => 'CS 112',
                'description' => 'Fundamentals of Programming',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ], 
            [
                'course_code' => 'GE-US',
                'description' => 'Understanding the Self',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'GE-MMW',
                'description' => 'Mathematics in the Modern World',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'GE-PC',
                'description' => 'Purposive Communication',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'Math 1',
                'description' => 'Advance College Algebra',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'IT-1',
                'description' => 'Living in the IT Era',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'PATH-Fit 1',
                'description' => 'Movement Competency Training',
                'units' => '2',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'NSTP 1',
                'description' => 'National Service Training Program 1',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'GE-STS',
                'description' => 'Science, Technology and Society',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'GE-E',
                'description' => 'Ethics',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'GE-CW',
                'description' => 'The Contemporary World',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'CS 121',
                'description' => 'Discrete Structures 1',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'CS 122',
                'description' => 'Intermediate Programming',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ], 
            [
                'course_code' => 'CS 123',
                'description' => 'Multimedia Systems and Technology',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '2',
            ], 
            [
                'course_code' => 'GE-BC',
                'description' => 'Business Correspondence',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'PATH-Fit 2',
                'description' => 'Exercise-based Fitness Activities',
                'units' => '2',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ], 
            [
                'course_code' => 'NSTP 2',
                'description' => 'National Service Training Program 2',
                'units' => '3',
                'year_level' => 'First Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 211',
                'description' => 'Discrete Structures 2',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 212',
                'description' => 'Object-Oriented Programming',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 213',
                'description' => 'Data Structures and Algorithms',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 214',
                'description' => 'Embedded Systems',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'GE-Stat',
                'description' => 'Descriptive and Inferential Statistics',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'Entrep 1',
                'description' => 'The Entrepreneurial Mind',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'GE-AA',
                'description' => 'Art Appreciation',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'PATH-Fit 3',
                'description' => 'Menu of Dance, Sports, Martial Arts, Group Exercise, Outdoor and Adventures Activity',
                'units' => '2',
                'year_level' => 'Second Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 221',
                'description' => 'Algorithms and Complexities',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 222',
                'description' => 'Information Management',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 223',
                'description' => 'Web Systems and Technologies 1',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 224',
                'description' => 'Computational Science',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'Ecos 1',
                'description' => "People and the Earth's Ecosystem",
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'GE-RPH',
                'description' => 'Readings in Philippine History',
                'units' => '3',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'PATH-Fit 4',
                'description' => 'Menu of Dance, Sports, Martial Arts, Group Exercise, Outdoor and Adventure Activities',
                'units' => '2',
                'year_level' => 'Second Year',
                'term_id' => '2',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 311',
                'description' => 'Automata Theory and Formal Languages',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 312',
                'description' => 'Architecture and Organization',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 313',
                'description' => 'Information Assurance and Security',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 314',
                'description' => 'Elective 1',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 315',
                'description' => "'Application Dev't & Emerging Technologies'",
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 316',
                'description' => 'Web Systems and Technologies',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'Rizal',
                'description' => 'Life and Works of Rizal',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '1',
                'subject_type' => 'Minor',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 321',
                'description' => 'Programming Languages',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 322',
                'description' => 'Software Enginering 1',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 323',
                'description' => 'Social Issues and Professional Practice 1',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 324',
                'description' => 'Elective 2',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 325',
                'description' => 'Mobile Computing 1',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '2',
            ],
            [
                'course_code' => 'CS 326',
                'description' => 'Modeling and Simulation',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '2',
            ],
            [
                'course_code' => 'CS 327',
                'description' => 'Data Mining Concepts and Techniques',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 328',
                'description' => 'Machine Learning',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 331',
                'description' => 'Practicum(324 hours)',
                'units' => '3',
                'year_level' => 'Third Year',
                'term_id' => '3',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 411',
                'description' => 'Human Computer Interaction',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 412',
                'description' => 'Operating Systems',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 413',
                'description' => 'Software Engineering 2',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 414',
                'description' => 'CS Thesis Writing 1',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
            [
                'course_code' => 'CS 415',
                'description' => 'Elective 3',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 416',
                'description' => 'Mobile Computing 2',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '1',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '2',
            ],
            [
                'course_code' => 'CS 421',
                'description' => 'Network and Communications',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'Yes',
                'lab_type' => '1',
            ],
            [
                'course_code' => 'CS 422',
                'description' => 'CS Thesis Writing 2',
                'units' => '3',
                'year_level' => 'Fourth Year',
                'term_id' => '2',
                'subject_type' => 'Major',
                'laboratory' => 'No',
                'lab_type' => '0',
            ],
        ]);
    }
}
